-- Table to store user-generated API keys for external agent access
CREATE TABLE public.user_api_keys (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name text,
    hashed_key text NOT NULL UNIQUE,
    key_prefix text NOT NULL, -- e.g., first 8 chars of the key for identification
    created_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    expires_at timestamptz -- For future implementation of key expiry
);

-- Enable Row Level Security
ALTER TABLE public.user_api_keys ENABLE ROW LEVEL SECURITY;

-- Policies for user_api_keys
-- Users can select their own API key records
CREATE POLICY "Allow users to select their own API keys"
ON public.user_api_keys
FOR SELECT
USING (auth.uid() = user_id);

-- Users can insert new API key records for themselves
CREATE POLICY "Allow users to insert their own API keys"
ON public.user_api_keys
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can update the name and last_used_at of their own API key records
CREATE POLICY "Allow users to update their own API keys"
ON public.user_api_keys
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id); -- Redundant USING for UPDATE, but common pattern

-- Users can delete their own API key records
CREATE POLICY "Allow users to delete their own API keys"
ON public.user_api_keys
FOR DELETE
USING (auth.uid() = user_id);

-- Optional: Add comments to table and columns for clarity
COMMENT ON TABLE public.user_api_keys IS 'Stores API keys generated by users for external agent access.';
COMMENT ON COLUMN public.user_api_keys.name IS 'User-friendly name for the API key (e.g., ''Claude Desktop Key'').';
COMMENT ON COLUMN public.user_api_keys.hashed_key IS 'Bcrypt hash of the actual API key.';
COMMENT ON COLUMN public.user_api_keys.key_prefix IS 'First few characters of the API key for display and identification by the user.';
COMMENT ON COLUMN public.user_api_keys.last_used_at IS 'Timestamp of when the key was last successfully used.';
COMMENT ON COLUMN public.user_api_keys.expires_at IS 'Optional timestamp for when the key should expire.';

-- Create an index on user_id for faster lookups
CREATE INDEX idx_user_api_keys_user_id ON public.user_api_keys(user_id);

-- Create an index on hashed_key for faster lookups during key validation
CREATE INDEX idx_user_api_keys_hashed_key ON public.user_api_keys(hashed_key);
